Added the new demo folder along with new instructions on getting started
BlinkID/blinkid-in-browser pull request #138
Opened 2024-07-04 14:25 UTC by Hitman666

2024-07-05 08:29 UTC, ivancuric requested changes
Please check out the individual comments for specifics.

On the topic of the tone of the docs – it's very friendly and encouraging, however it has a lot of unnecessary "fluff" and humor, and I feel it fails to help the user understand why things need to be done in a certain way.

2024-07-05 08:29 UTC, ivancuric commented on README.md
> +- in your terminal, clone [this](https://github.com/BlinkID/blinkid-in-browser) repo with `git clone https://github.com/BlinkID/blinkid-in-browser`
Doesn't have to be a terminal. Do we need to explain how to clone a repository?

2024-07-05 08:29 UTC, ivancuric commented on README.md
> +- open [http://localhost:5173/](http://localhost:5173/) and point your ID towards the camera
Might be a different open port depending on vite's startup.

2024-07-05 08:29 UTC, ivancuric commented on README.md
> +If you prefer a short video for running this project, feel free to check it out [here](https://www.youtube.com/watch?v=c0ZA8af9oBc).
Video is good, the audio however is quiet and only present on the left speaker.

2024-07-05 08:29 UTC, ivancuric commented on examples/getting-started/README.md
> +Test this repo out in under a minute on your machine (if you have Node and Git installed) by doing the following steps:
How did we get to under a minute here?

2024-07-05 08:29 UTC, ivancuric commented on examples/getting-started/README.md
> +If you want to recreate this project from scratch, here's the step by step guide...
Why the ellipsis?

2024-07-05 08:29 UTC, ivancuric commented on examples/getting-started/README.md
> +Let's set the stage: you're running a car rental business, and your customers have to enter their driver license information in a web form on your website. This process is usually error prone, and of
This section is a sales pitch, and has no place in technical documentation, but on product marketing pages.

2024-07-05 08:29 UTC, ivancuric commented on examples/getting-started/README.md
> +- Git – here’s a fun [getting started tutorial](https://nikola-breznjak.com/blog/miscellaneou/learn-git-fast-job-depends/) in case you’re new to it
No self-promotion, please. Share official resources. 

Additionally, this section covers the necessary tools required to run this repo. The linked article even skips that step, referring the user to the official site.

> To install Git, go to the [official website](https://try.github.io/) and download the executable for your machine. I’m not going into the installation details

2024-07-05 08:29 UTC, ivancuric commented on examples/getting-started/README.md
> +- Node.js – here’s a free but a bit outdated [step by step guide/book](https://leanpub.com/meantodo) for both Windows and Mac. Or, really, just go to the [main website](https://nodejs.org/en) and dow
No need to link learning resources. This is a getting started guide.

Say which version of node is required, the best way to install it, and to use a node version manager, otherwise we can end up in cases where root access is required for running npm scripts.

2024-07-05 08:29 UTC, ivancuric commented on examples/getting-started/README.md
> +In case you're wondering why that is even important, then a very long explanation is [here](https://vitejs.dev/guide/why.html#the-problems), and a very quick, but mouthfull, answer is that:
No need to explain in detail, just that it's the industry standard quick-start server these days.

2024-07-05 08:29 UTC, ivancuric commented on examples/getting-started/README.md
> +This is a **very important step**, that often gets overlooked! So, please make sure to copy the `resources` folder (`found in node_modules/@microblink/blinkid-in-browser-sdk/resources`) into the `pub
Explain why, and what the `public` folder does.

2024-07-05 08:29 UTC, ivancuric commented on examples/getting-started/README.md
> +```
Add language tags to code blocks, ie:  "```html"
```html
<p>Hello World</p>
```

2024-07-05 08:29 UTC, ivancuric commented on examples/getting-started/README.md
> +Line by line:
This should be a part of the code in form of comments for easier following.

2024-07-05 08:29 UTC, ivancuric commented on examples/getting-started/main.js
> +const LICENSE = ''; // go to https://developer.microblink.com/ to generate a license
Code formatting. Use https://prettier.io/

2024-07-05 08:29 UTC, ivancuric commented on examples/getting-started/README.md
> +If you're interested and haven't used Vite before, I encourage you to check out the code. It showcases the ability to use the `import` command (which traditionally can't be used in the plain JS world
> which traditionally can't be used in the plain JS world without using a module bundler

This is false and outdated information

2024-07-11 15:18 UTC, Hitman666 commented on README.md
> +Test this repo out in under 3 minutes on your machine (if you have Node and Git installed) by doing the following steps:
Thanks, addressed as well 👍

2024-07-11 15:20 UTC, Hitman666 commented on README.md
> +- in your terminal, clone [this](https://github.com/BlinkID/blinkid-in-browser) repo with `git clone https://github.com/BlinkID/blinkid-in-browser`
Slightly changed the text here, but retained the clone command.

2024-07-11 15:23 UTC, Hitman666 commented on README.md
> +- open [http://localhost:5173/](http://localhost:5173/) and point your ID towards the camera
Adressed.

2024-07-11 15:24 UTC, Hitman666 commented on README.md
> +If you prefer a short video for running this project, feel free to check it out [here](https://www.youtube.com/watch?v=c0ZA8af9oBc).
Yeah, true. Will see if I get to recreating this. For now, will leave as is.

2024-07-15 12:09 UTC, closed without merging